path_data_baseline = 'data/data_baseline.csv'
path_data_future = 'data/future_ip.csv'
path_data_historical = 'data/2020-09-30_historical_ip.csv'
path_data = 'data'
reference_countries_and_regions = 'data/reference_countries_and_regions.csv'
